[HINT]
count=14
text1=スレに投下するときは、レスの内容を「ＳＪＩＳコピー」しよう。普通にコピーすると、ユニコードが ? になっちゃうよ。
text2=レイヤボックスを使うと、背景のＡＡに別のＡＡを上書き合成できるよ。でも、大量のユニコード空白に気をつけて！
text3=やる夫板II等のしたらば掲示板の１レスの限界は4096Byte。右下にそのコマの容量が表示されてるから確認してね。
text4=ユニコード文字は便利だけど、１文字あたり10Byte以上使うんだ。多用してるとすぐに１レスの容量限界になっちゃうよ。
text5=やる夫スレ雑談IRCチャットルームがオープンしてるよ。ピークは２０時～２４時くらいかな。来てみてね！
text6=レイヤボックス内のＡＡの、連続する空白部分は透過領域に設定出来るよ。ダブルクリックして灰色になるところが透過されるよ。
text7=右側の指定ドット位置に、マーカーのラインを表示出来るよ。幅の目安にするといいと思うな。
text8=Ctrl＋Ｆで検索窓が出てくるよ。範囲選択して、Ctrl＋F3すると、その文字列でファイル内検索ができるよ。
text9=Ctrl+PageUp(PageDown)で、複数開いてるファイルを移動出来るよ。
text10=複数行テンプレートの窓でCtrl+Tすると各ＡＡのサムネイルが見えるよ。
text11=枠挿入で右側に妙な空白が出来る場合は、枠編集で「上下の端数を埋める」のチェックを外しておこう。
text12=枠挿入の各内容は自由に編集できるよ。よく使うのを登録しておくと便利だよ。
text13=お燐をスレに出演させたら、OrinrinEditorスレで教えてくれると、それはとっても嬉しいなって。
text14=したらばの仕様変更で、一部の文字が文字化けするみたい。「機種依存文字を数値参照コピーする」をＯＮにしてみて。
